FROM node:18-alpine

# 设置非root用户
RUN addgroup -S app && adduser -S app -G app
USER app

WORKDIR /app

# 安装依赖
COPY --chown=app:app package.json pnpm-lock.yaml ./
RUN corepack enable && \
    pnpm install --frozen-lockfile

# 复制源码
COPY --chown=app:app . .

# 开发模式运行
CMD ["pnpm", "dev"]